name: Build Push Image

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Which image do you wish to build?'
        required: true
        type: string

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        id: get-tag
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build docker images
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.event.inputs.directory }}
          tags: |
            ghcr.io/iameskild/${{ github.event.inputs.directory }}:${{ steps.get-tag.outputs.sha }}
          push: true